# Docker schema version definition
# Check the compatibility matrix with the current schema version in the File Creation Reference.
# https://docs.docker.com/compose/compose-file/
version: "3.8"

# Services or Containers List definition
services:
  db:
    image: mysql:latest
    container_name: mysql-capston-ex
    ports:
      - 3306:3306
    volumes:
      - ./data/:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
    #      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=capston
      - MYSQL_DATABASE=capston-ex
      - MYSQL_USER=capston_user_ex
      - MYSQL_PASSWORD=capstonPassword
      - TZ=Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis_container:
    image: redis
    container_name: redis-capston-ex
    ports:
      - 6379:6379